version: 0.3.0.{build}
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
environment:
  COVERALL_TOKEN:
    secure: Xldcm2fCjAGzhwY/OF7sBXiuamRWDD6H7icrLQHRL+DmyJgdOoPMryBfEgvJai3Q
test_script:
- ps: >-
    .\runtests.ps1
