version: 0.7.2.{build}
before_build:
- ps: >-
    cd ./LiteApi

    dotnet restore
build:
  project: LiteApi/LiteApi.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd LiteApi

    cd LiteApi.Tests

    dotnet test
